assets: /home/zijianwang/openpi/third_party/LIBERO-PRO/libero/libero/./assets
bddl_files: /home/zijianwang/openpi/third_party/LIBERO-PRO/libero/libero/./bddl_files
benchmark_root: /home/zijianwang/openpi/third_party/LIBERO-PRO/libero/libero
datasets: /home/zijianwang/openpi/third_party/LIBERO-PRO/libero/libero/../datasets
init_states: /home/zijianwang/openpi/third_party/LIBERO-PRO/libero/libero/./init_files
